# Generated by Django 5.2.11 on 2026-04-11 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='cultures_cu_nom_ecf61d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en hectares', max_digits=6)),
                ('type_sol', models.CharField(blank=True, help_text='Type de sol (argileux, sableux, etc.)', max_length=100)),
                ('localisation', models.CharField(blank=True, help_text="Description de l'emplacement", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='accounts.ferme')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CultureParcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_semis', models.DateField()),
                ('date_recolte_prevue', models.DateField(blank=True, null=True)),
                ('date_recolte_reelle', models.DateField(blank=True, null=True)),
                ('rendement', models.DecimalField(blank=True, decimal_places=2, help_text='Production en kg', max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelles_associees', to='cultures.culture')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures_associees', to='cultures.parcelle')),
            ],
            options={
                'verbose_name': 'Culture sur parcelle',
                'verbose_name_plural': 'Cultures sur parcelles',
                'ordering': ['-date_semis'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LABOUR', 'Labour'), ('SEMIS', 'Semis'), ('IRRIGATION', 'Irrigation'), ('FERTILISATION', 'Fertilisation'), ('DESHERBAGE', 'Désherbage'), ('TRAITEMENT', 'Traitement phytosanitaire'), ('RECOLTE', 'Récolte')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('intrants_utilises', models.CharField(blank=True, help_text='Engrais, pesticides, etc.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_agricoles', to=settings.AUTH_USER_MODEL)),
                ('culture_parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='cultures.cultureparcelle')),
            ],
            options={
                'verbose_name': 'Activité agricole',
                'verbose_name_plural': 'Activités agricoles',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='cultures_ac_date_e9ef89_idx'), models.Index(fields=['type'], name='cultures_ac_type_d9e117_idx'), models.Index(fields=['culture_parcelle'], name='cultures_ac_culture_1b093b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['ferme'], name='cultures_pa_ferme_i_ca5269_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['nom'], name='cultures_pa_nom_bc1a5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelle',
            unique_together={('ferme', 'nom')},
        ),
        migrations.AddIndex(
            model_name='cultureparcelle',
            index=models.Index(fields=['parcelle'], name='cultures_cu_parcell_251105_idx'),
        ),
        migrations.AddIndex(
            model_name='cultureparcelle',
            index=models.Index(fields=['culture'], name='cultures_cu_culture_c58d30_idx'),
        ),
        migrations.AddIndex(
            model_name='cultureparcelle',
            index=models.Index(fields=['date_semis'], name='cultures_cu_date_se_117845_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cultureparcelle',
            unique_together={('parcelle', 'date_semis')},
        ),
    ]
