# Generated by Django 4.2.7 on 2026-04-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero_identification', models.CharField(max_length=50, unique=True)),
                ('espece', models.CharField(choices=[('vache', 'Vache'), ('taureau', 'Taureau'), ('veau', 'Veau'), ('brebis', 'Brebis'), ('belier', 'Bélier'), ('agneau', 'Agneau')], max_length=20)),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('malade', 'Malade'), ('reproduction', 'En reproduction'), ('vente', 'À vendre')], default='actif', max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='animals/')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vaccin', 'Vaccin'), ('medicament', 'Médicament'), ('vermifuge', 'Vermifuge'), ('soins', 'Soins')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('date_prochaine', models.DateField(blank=True, null=True)),
                ('veterinaire', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='fermeapp.animal')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'ordering': ['-date'],
            },
        ),
    ]
