# Generated by Django 5.2.11 on 2026-04-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ferme_user_ferme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_users', 'Peut gérer les utilisateurs de sa ferme'), ('can_view_reports', 'Peut consulter tous les rapports'), ('can_export_data', 'Peut exporter les données')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
