# Generated by Django 5.2.8 on 2026-03-27 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espèce',
                'verbose_name_plural': 'Espèces',
            },
        ),
        migrations.CreateModel(
            name='LotPondeuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_sujets', models.PositiveIntegerField()),
                ('date_mise_en_place', models.DateField()),
                ('race', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_crees', to=settings.AUTH_USER_MODEL)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='cheptel.espece')),
            ],
            options={
                'verbose_name': 'Lot de pondeuses',
                'verbose_name_plural': 'Lots de pondeuses',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_arrivee', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('VENDU', 'Vendu'), ('DECEDE', 'Décédé')], default='ACTIF', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaux_crees', to=settings.AUTH_USER_MODEL)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animaux', to='cheptel.espece')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaux', to='cheptel.lotpondeuses')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
                'ordering': ['-date_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VACCIN', 'Vaccination'), ('TRAITEMENT', 'Traitement'), ('MALADIE', 'Maladie')], max_length=20)),
                ('date', models.DateField()),
                ('produit', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='cheptel.animal')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ComptageOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptages_crees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptages', to='cheptel.lotpondeuses')),
            ],
            options={
                'verbose_name': "Comptage d'œufs",
                'verbose_name_plural': "Comptages d'œufs",
                'unique_together': {('lot', 'date')},
            },
        ),
    ]
