# Generated by Django 5.2.8 on 2026-03-28 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheptel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.AlterUniqueTogether(
            name='comptageoeufs',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['identifiant'], name='cheptel_ani_identif_40b07d_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['statut'], name='cheptel_ani_statut_f2717c_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['espece'], name='cheptel_ani_espece__5e74cd_idx'),
        ),
        migrations.AddIndex(
            model_name='comptageoeufs',
            index=models.Index(fields=['date'], name='cheptel_com_date_6fbe35_idx'),
        ),
        migrations.AddIndex(
            model_name='espece',
            index=models.Index(fields=['nom'], name='cheptel_esp_nom_bdd291_idx'),
        ),
        migrations.AddIndex(
            model_name='lotpondeuses',
            index=models.Index(fields=['espece'], name='cheptel_lot_espece__70730e_idx'),
        ),
        migrations.AddConstraint(
            model_name='comptageoeufs',
            constraint=models.UniqueConstraint(fields=('lot', 'date'), name='unique_lot_date'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom'], name='cheptel_pro_nom_eb5986_idx'),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traitements', to='cheptel.produit'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['date'], name='cheptel_tra_date_67aea1_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['type'], name='cheptel_tra_type_71e9ed_idx'),
        ),
    ]
