# Generated by Django 5.2.11 on 2026-04-08 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
        ('cheptel', '0002_produit_alter_comptageoeufs_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='animaux/'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='rappel_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre_morts', models.PositiveIntegerField(default=0, help_text="Nombre d'animaux morts aujourd'hui")),
                ('oeufs_pondus', models.PositiveIntegerField(default=0, help_text="Nombre d'œufs pondus aujourd'hui")),
                ('aliment_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Aliments consommés (kg)', max_digits=10, null=True)),
                ('eau_litres', models.DecimalField(blank=True, decimal_places=2, help_text='Eau servie (litres)', max_digits=10, null=True)),
                ('sujets_malades', models.PositiveIntegerField(default=0, help_text="Nombre d'animaux malades")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='accounts.ferme')),
            ],
            options={
                'verbose_name': 'Rapport journalier',
                'verbose_name_plural': 'Rapports journaliers',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='cheptel_rap_date_b632a6_idx'), models.Index(fields=['ferme', 'date'], name='cheptel_rap_ferme_i_564e0e_idx')],
                'constraints': [models.UniqueConstraint(fields=('ferme', 'date'), name='unique_rapport_ferme_date')],
            },
        ),
    ]
