# Generated by Django 5.2.11 on 2026-04-08 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
        ('cheptel', '0003_animal_photo_traitement_rappel_le_rapportjournalier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ferme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='accounts.ferme'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['ferme'], name='cheptel_ani_ferme_i_e6dfe1_idx'),
        ),
    ]
