# Generated by Django 5.2.11 on 2026-04-08 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
        ('cheptel', '0004_animal_ferme_animal_cheptel_ani_ferme_i_e6dfe1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lotpondeuses',
            name='ferme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='accounts.ferme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traitement',
            name='ferme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='accounts.ferme'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='lotpondeuses',
            index=models.Index(fields=['ferme'], name='cheptel_lot_ferme_i_4a9128_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['ferme'], name='cheptel_tra_ferme_i_fd3ef6_idx'),
        ),
    ]
