# Generated by Django 4.2.7 on 2026-07-24 19:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPENSE', 'Dépense'), ('RECETTE', 'Recette')], max_length=10)),
                ('categorie', models.CharField(choices=[('SALAIRE', 'Salaire'), ('VETERINAIRE', 'Frais vétérinaires'), ('LOCATION', 'Location'), ('TRANSPORT', 'Transport'), ('AUTRE_DEPENSE', 'Autre dépense'), ('VENTE_ANIMAUX', "Vente d'animaux"), ('VENTE_OEUFS', "Vente d'œufs"), ('VENTE_CULTURES', 'Vente de récoltes'), ('AUTRE_RECETTE', 'Autre recette')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.ferme')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
