# Generated by Django 5.2.11 on 2026-04-29 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('unite', models.CharField(choices=[('KG', 'Kilogramme (kg)'), ('L', 'Litre (L)'), ('SAC', 'Sac (50kg)'), ('BONBONNE', 'Bonne (20L)'), ('UNITE', 'Pièce unitaire')], default='KG', max_length=20)),
                ('emplacement', models.CharField(blank=True, max_length=100)),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fournisseur_principal', models.CharField(blank=True, max_length=100)),
                ('prix_moyen_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='accounts.ferme')),
            ],
            options={
                'verbose_name': 'Produit de stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', '📥 Entrée (achat, production)'), ('SORTIE', '📤 Sortie (consommation, vente)')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.produitstock')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='produitstock',
            index=models.Index(fields=['ferme'], name='stocks_prod_ferme_i_9326db_idx'),
        ),
        migrations.AddIndex(
            model_name='produitstock',
            index=models.Index(fields=['seuil_alerte'], name='stocks_prod_seuil_a_7d29c5_idx'),
        ),
        migrations.AddIndex(
            model_name='produitstock',
            index=models.Index(fields=['quantite_actuelle'], name='stocks_prod_quantit_41a1fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produitstock',
            unique_together={('ferme', 'nom')},
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['produit'], name='stocks_mouv_produit_68ee45_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['date'], name='stocks_mouv_date_d0cc3b_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type'], name='stocks_mouv_type_23c132_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['produit', 'date'], name='stocks_mouv_produit_d447fd_idx'),
        ),
    ]
